### ISSUE TITLE
Getting a FileNotFoundException for camera._convertVideoFormats Ricoh Theta X

### ISSUE THREAD

**Issue by joseandroidengineer** [ricohapi/theta-api-specs#13]
Currently the Ricoh Theta Camera X works well when taking images and even recording. However, when converting the video format of the video just taken, I get a FileNotFoundException.java which isn't the case because I see the file in the camera itself.

This works well with other cameras and I have no issue except only for the Ricoh Theta Cam X

I know the THETA app handles it well, just wondering anything special I need to do for this particular camera.
Only thing I'm doing differently is NOT passing "projectionType", "codec", and "topBottomCorrection"

Thank you

**Comment by codetricity** [comment]
If you're not converting the projectionType, codec, or topBottomCorrection, why do you need to apply [camera._convertVideoFormats](https://github.com/ricohapi/theta-api-specs/blob/main/theta-web-api-v2.1/commands/camera._convert_video_formats.md) to the video file from the RICOH THETA X?  Wouldn't it have not effect on the video file from the X?  I don't use this API myself.  However, I'm just wondering how people are using it with the THETA X video file.  Thanks.

**Comment by joseandroidengineer** [comment]
Hey! I realized for the THETA X I don't need to use camera._convertVideoFormats since it seems to be processed within the camera itself. Thanks for clearing this up, in the api docs it should be specified that its not supported on the THETA X.

Much appreciated!

**Comment by codetricity** [comment]
I agree that it's kind of odd that the documentation indicates that the X is supported, but the command doesn't do anything.  

I haven't tested this.  On the THETA X does [camera._convertVideoFormats](https://github.com/ricohapi/theta-api-specs/blob/main/theta-web-api-v2.1/commands/camera._convert_video_formats.md) not return the fileUrl?

BTW, I'm curious to learn what type of app you're building with the THETA X.
