### ISSUE TITLE
USB API DeleteObject call

### ISSUE THREAD

**Issue by karmelcorn** [ricohapi/theta-api-specs#33]
Hi, 

I am using the MTP example and I want to delete the video file from the Ricoh camera. 

Using the following code 

`            res = command.Execute(MtpOperationCode.DeleteObject, new uint[2] { objectHandles[num - 1], 0x00000000 }, null);
`
I could not delete the object (video file) on the Ricoh camera, even though the `RespondCode = OK`

**Comment by karmelcorn** [comment]
On further testing, I realized that the `DeleteObject` command delete the `ObjectHandler` but not the actual file from the disk. 

After the `DeleteObject` command delete `GetNumObjects ` return one less object and the file disappears from the folder on the camera view (Theta X) but if you look into the folder (`This PC\RICOH THETA X\Fixed storage\DCIM\100RICOH`) on the computer, the file is still there.

**Comment by DaisukeHohjoh** [comment]
Hi @karmelcorn ,

> the deletion is not updated to the windows explorer. If you disconnect the camera and reconnect it via usb, the windows explorer will be updated without the files that have been deleted.

I am sorry that this phenomenon is the limitation. Because Theta side does not notify the deletion to windows explorer, when the files are deleted by other process.

Best regards,
Daisuke Hohjoh

**Comment by karmelcorn** [comment]
Hi @DaisukeHohjoh ,

Thank you for your reply. No worries. This should not be a problem for the purpose of my application. So I will go ahead and close this thread.
