### ISSUE TITLE
How to set ISO of android Ricoh Theta X using Java?

### ISSUE THREAD

**Issue by boyapdao** [ricohapi/theta-api-specs#42]
I am using THETA Plug-in to set iso for thetaX camera 360.
However I didn't notice any changes on the camera.

This is code i tried:

`
import theta360.hardware.Camera;

int value = 50; // value of 50 to 3200 can be set.
Camera thetaCamera = ThetaCapturer.getThetaCamera(); // instance of Camera
Camera.Parameters parameters = thetaCamera.getParameters();
parameters.set(Camera.Parameters.RIC_EXPOSURE_MODE, Camera.Parameters.RIC_MANUAL_EXPOSURE);
parameters.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_ISO_FRONT, value);
parameters.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_ISO_REAR, value);
thetaCamera.setParameters(parameters);
`
Is there any solution for this?
Plugin version: 3.3.0, link: [camera-plugin-api](https://github.com/ricohapi/theta-plugin-sdk)
Below are the documents I followed:
Theta-api-specs: [iso-sensitivity](https://github.com/ricohapi/theta-api-specs/blob/main/ricoh-theta-plugin/camera-api.md#iso-sensitivity)
Theta-plugin-webrtc-sample: [CameraOption](https://github.com/ricohapi/theta-plugin-webrtc-sample/blob/master/app/src/main/java/com/theta360/pluginapplication/webrtc/sample/model/CameraOption.java)

**Comment by DaisukeHohjoh** [comment]
Hi @boyapdao ,

I attached some sample code.

**Case1. Manual exposure mode, ISO3200, 1/100sec**

```
        p.set(Camera.Parameters.RIC_EXPOSURE_MODE, Camera.Parameters.RIC_MANUAL_EXPOSURE)
        p.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_ISO_FRONT, 18)  //ISO3200
        p.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_ISO_REAR, 18)   //ISO3200
        p.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_TIME_FRONT, 24) //1/100sec
        p.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_TIME_REAR, 24)  //1/100sec
```

ISO3200 is 18, please refer to Theta Camera API document [here](https://github.com/ricohapi/theta-api-specs/blob/main/ricoh-theta-plugin/camera-api.md#iso-sensitivity).
Please set both "ISO sensitivity" and "Shutter speed" for manual exposure mode.

----

**Case2. ISO sensitivity priority mode, ISO3200, shutter speed is auto**

```
        p.set(Camera.Parameters.RIC_EXPOSURE_MODE, Camera.Parameters.RIC_AUTO_EXPOSURE_S)
        p.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_ISO_FRONT, 18)  //ISO3200
        p.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_ISO_REAR, 18)   //ISO3200
```

----

**Case3. Shutter speed priority mode, 1/100sec, ISO sensitivity is auto**

```
         p.set(Camera.Parameters.RIC_EXPOSURE_MODE, Camera.Parameters.RIC_AUTO_EXPOSURE_T)
        p.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_TIME_FRONT, 24) //1/100sec
        p.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_TIME_REAR, 24)  //1/100sec

```

And please noted as well that manual exposure mode is available only for normal still capture mode. In other words, HDR mode can use only auto exposure mode `Camera.Parameters.RIC_AUTO_EXPOSURE_P` .

Best regards,
Daisuke Hohjoh

**Comment by boyapdao** [comment]
I am setting the values: Exposure Compensation, ISO and shutterSpeed.
Below is the code I implemented:

```
boolean isSetEv = false; // mock mode ev or (iso, shutter speed)
String json;
if (isSetEv) {
    json = "{ev=1.0, iso=0.0, shutter_speed=0.0}"; // mock data

    // Need shutter Speed and ISO in automatic mode
    p.set(Camera.Parameters.RIC_EXPOSURE_MODE, Camera.Parameters.RIC_AUTO_EXPOSURE_P);
} else {
    json = "{ev=0.0, iso=2500.0, shutter_speed=0.03333333}"; // mock data

    // Need Expose Value in automatic mode
    p.set(Camera.Parameters.RIC_EXPOSURE_MODE, Camera.Parameters.RIC_MANUAL_EXPOSURE);
}
Iso iso = Iso.getValue(json.getIso());
ShutterSpeed shutter = ShutterSpeed.getValue(json.getShutterSpeed());

p.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_ISO_FRONT, iso.getIndexValue());
p.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_ISO_REAR, iso.getIndexValue());
p.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_TIME_FRONT, shutter.getIndexValue());
p.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_TIME_REAR, shutter.getIndexValue());

p.setExposureCompensation(json.getEv());
```
Am I doing this correctly? 
Please let me know which modes need to be set when switching between the values ​​(iso, shutter speed) and (Expose Value).

**Comment by DaisukeHohjoh** [comment]
Thanks.

```
json = "{ev=0.0, iso=2500.0, shutter_speed=0.03333333}"; // mock data
....
Iso iso = Iso.getValue(json.getIso());
ShutterSpeed shutter = ShutterSpeed.getValue(json.getShutterSpeed());
```

This code will set ISO=2500.0, and shutter=0.03333333 to Camera.Parameters. But, Camera API parameters defines like following. Please refer to [this page](https://github.com/ricohapi/theta-api-specs/blob/main/ricoh-theta-plugin/camera-api.md#iso-sensitivity).

ISO Sensitivity

| Value | Description |
|:--:|:--:|
|0|ISO50|
|1|ISO64|
|....|....|
|15|ISO1600|
|....|....|
|18|ISO3200|

Shutter Speed

| Value | Description |
|:--:|:--:|
|0|1/25600|
|1|1/20000|
|....|....|
|15|1/800sec|
|....|....|
|62|60sec|

So, setting value should be corrected like following.

```
json = "{ev=0.0, iso=2500.0, shutter_speed=0.03333333}"; // mock data
↓
json = "{ev=0, iso=17, shutter_speed=29}"; // mock data
```

But your values should be correct and effect for WebAPI. Sorry for your confusion.

Best regards,
Daisuke Hohjoh

**Comment by boyapdao** [comment]
Thanks for your supports.
I converted the value via `getIndexValue()` method.
```
Iso iso = Iso.getValue(json.getIso());
ShutterSpeed shutter = ShutterSpeed.getValue(json.getShutterSpeed());
iso.getIndexValue();
shutter.getIndexValue();
```
I tried it and applied it successfully.
But never mind it, what I want to ask here is when I switch back and forth between apply (iso, shutterSpeed) and Expose value through `p.setExposureCompensation(json.getEv())` function.
```
if (isSetEv) {
    p.set(Camera.Parameters.RIC_EXPOSURE_MODE, Camera.Parameters.RIC_AUTO_EXPOSURE_P);
    // I want to reset the ISO value and shutter speed.
} else {
    p.set(Camera.Parameters.RIC_EXPOSURE_MODE, Camera.Parameters.RIC_MANUAL_EXPOSURE);
    // I want to reset the expose value.
}
```
Am I using the above mode correctly? What should I do when I want to reset Expose value and ISO, shutter speed value?

**Comment by DaisukeHohjoh** [comment]
I'm not sure if I've answered your question, but....

> ```
> if (isSetEv) {
>     p.set(Camera.Parameters.RIC_EXPOSURE_MODE, Camera.Parameters.RIC_AUTO_EXPOSURE_P);
>     // I want to apply Expose value and reset iso and shutterSpeed ​​value
> } else {
>     p.set(Camera.Parameters.RIC_EXPOSURE_MODE, Camera.Parameters.RIC_MANUAL_EXPOSURE);
>     //  I want to apply iso and shutterSpeed value and reset the Expose value.
> }
> ```

`Camera.Parameters.RIC_AUTO_EXPOSURE_P` is auto exposure mode, this mode will ignore `iso` and `shutterSpeed` values but apply only `exposure compensation` value.

`Camera.Parameters.RIC_MANUAL_EXPOSURE` is manual exposure mode, this mode will ignore `exposure compensation` value but apply `iso` and `shutterSpeed` values.

In other words, in my understanding, we don't need reset `iso` and `shutterSpeed` values (=set some kind of default values) when using ` RIC_AUTO_EXPOSURE_P`.

Also, we don't need reset `exposure compensation` value (=set some kind of default value) when using `Camera.Parameters.RIC_MANUAL_EXPOSURE`.

**Comment by boyapdao** [comment]
Thanks for your solutions, i have solved it.
