### ISSUE TITLE
How to set ShutterSpeed of android Ricoh Theta X using Java?

### ISSUE THREAD

**Issue by boyapdao** [ricohapi/theta-api-specs#43]
I am using THETA Plug-in to set shutter speed for thetaX camera 360.
However I didn't notice any changes on the camera.

This is code i tried:
`
import theta360.hardware.Camera;

String value = "1/30"; // value of 1/16000 to 60 can be set.
Camera thetaCamera = ThetaCapturer.getThetaCamera(); // instance of Camera
Camera.Parameters parameters = thetaCamera.getParameters();
parameters.set(Camera.Parameters.RIC_EXPOSURE_MODE, Camera.Parameters.RIC_MANUAL_EXPOSURE);
parameters.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_TIME_FRONT, value);
parameters.set(Camera.Parameters.RIC_MANUAL_EXPOSURE_TIME_REAR, value);
thetaCamera.setParameters(parameters);
`
Is there any solution for this?
Plugin version: 3.3.0, link: [plugin](https://github.com/ricohapi/theta-plugin-sdk)

Below are the documents I followed:
Theta-api-specs: [shutter-speed](https://github.com/ricohapi/theta-api-specs/blob/main/ricoh-theta-plugin/camera-api.md#shutter-speed)
Theta-plugin-webrtc-sample: [CameraOption](https://github.com/ricohapi/theta-plugin-webrtc-sample/blob/master/app/src/main/java/com/theta360/pluginapplication/webrtc/sample/model/CameraOption.java)

**Comment by DaisukeHohjoh** [comment]
Hi @boyapdao ,

Please refer to my this comment.
https://github.com/ricohapi/theta-api-specs/issues/42#issuecomment-2204972415

Best regards,
Daisuke Hohjoh
