### ISSUE TITLE
The parameter "security" of "camera._setAccessPoint" is a mandatory parameter for THETA X.

### ISSUE THREAD

**Issue by shrhdk** [ricohapi/theta-api-specs#8]
The document describes the parameter `security` is optional, but it is actually a required parameter on THETA X 1.40.0.

https://github.com/ricohapi/theta-api-specs/blob/5a39ce5421286fd21bd9505576658d8e5019e797/theta-web-api-v2.1/commands/camera._set_access_point.md?plain=1#L20

----

THETA X returns a `missingParameter` error when executing the `camera._setAccessPoint` command without `security`.

```http
POST http://127.0.0.1:8080/osc/commands/execute HTTP/1.1
Content-Type: application/json; charset=UTF-8
Content-Length: 68
Accept: application/json
X-XSRF-Protected: 1

{"name":"camera._setAccessPoint","parameters":{"ssid":"DUMMY_SSID"}}
```

```http
HTTP/1.1 400 Bad Request
Connection: Keep-Alive
User-Agent: Dalvik/2.1.0 (Linux; U; Android 10; RICOH THETA X Build/QKQ1.210402.001)
X-Content-Type-Options: nosniff
Content-Length: 139
Content-Type: application/json; charset=utf-8

{"error":{"code":"missingParameter","message":"Any required parameter  is not specified."},"name":"camera._setAccessPoint","state":"error"}
```

----

THETA X returns OK when executing the command with `security`.

```http
POST http://127.0.0.1:8080/osc/commands/execute HTTP/1.1
Content-Type: application/json; charset=UTF-8
Content-Length: 86
Accept: application/json
X-XSRF-Protected: 1

{"name":"camera._setAccessPoint","parameters":{"ssid":"DUMMY_SSID","security":"none"}}
```

```http
HTTP/1.1 200 OK http://127.0.0.1:8080/osc/commands/execute
Connection: Keep-Alive
User-Agent: Dalvik/2.1.0 (Linux; U; Android 10; RICOH THETA X Build/QKQ1.210402.001)
X-Content-Type-Options: nosniff
Content-Length: 48
Content-Type: application/json; charset=utf-8

{"name":"camera._setAccessPoint","state":"done"}
```

----

I confirmed that THETA V 3.81.1 returns OK when executing the command without `security`.

**Comment by DaisukeHohjoh** [comment]
@shrhdk 
Sorry for your inconvenience.
RICOH double-checked `camera._setAccessPoint` with/without `security` option, then found a mismatch between the document and actual behavior.

----

#### THETA V/Z1

- `security` is **mandatory** parameter when access point setting is **new added** by `camera._setAccessPoint`.
- `security` is **optional** parameter when access point setting is **overwritten** by `camera._setAccessPoint`.

#### THETA X FW1.40.0

- `security` is **always mandatory** parameter of `camera._setAccessPoint`.

----

#### TODO

- RICOH need to fix the document of `security` option.
https://github.com/ricohapi/theta-api-specs/blob/5a39ce5421286fd21bd9505576658d8e5019e797/theta-web-api-v2.1/commands/camera._set_access_point.md?plain=1#L20
- THETA X needs to be fixed next firmware to behave the same as THETA V/Z1.

**Comment by DaisukeHohjoh** [comment]
>THETA X needs to be fixed next firmware to behave the same as THETA V/Z1.
THETA X firmware v2.00.0 fixes this issue to behave the same as THETA V/Z1.
